### PR TITLE
require the new ffmpeg-full codecs extension

### PR DESCRIPTION
**Pull request by gdesmott**

### CODE REVIEW

**Comment by gdesmott** [comment]
bot, build

**Comment by TingPing** [comment]
This is the wrong solution.

If you need ffmpeg you build ffmpeg. The extension exists for organizations who want to distribute the runtime but not distribute encumbered codecs. This has no relevance to this package.

**Comment by gdesmott** [comment]
Oh thanks, I didn't find much documentation about those extensions so was experimenting.

So I don't have to change anything and can just rely on the runtime having `org.freedesktop.Platform.html5-codecs` then?

**Comment by TingPing** [comment]
No, you build `ffmpeg` if you want `ffmpeg`...

https://github.com/flathub/io.github.celluloid_player.Celluloid/blob/master/io.github.celluloid_player.Celluloid.json#L90-L108

**Comment by gdesmott** [comment]
I was relying on the gstreamer ffmpeg decoder but I think openh264 should be enough (as soon as https://gitlab.gnome.org/GNOME/gnome-build-meta/issues/204 is fixed).

**Pull request closed without merging**
